### ISSUE TITLE
Query planner chooses names for anonymous result columns that might be identical to existing ones

### ISSUE THREAD

**Issue by cswinter** [cswinter/LocustDB#101]
It should ensure that all output column names are unique.

**Comment by virattara** [comment]
Can I pick this up? Also interested to know about your future plans related to this project.

**Comment by cswinter** [comment]
Please do! I think it just needs some changes to this function: https://github.com/cswinter/LocustDB/blob/e3e53fa6ecd7a6c53337bd017c600fa2e6c18ff1/src/engine/planning/query.rs#L347
There's also a related issue https://github.com/cswinter/LocustDB/issues/67 which should also be relatively easy to fix with some additional small changes to the parser/AST to propagate alias information. 

I don't currently expect to spend a lot of time on this project beyond bug fixes and the like.
When my schedule clears up a bit, I would like to actually build out some application (probably log storage/search) that would allow people to try out LocustDB more easily by just deploying a prebuilt docker image to their kube cluster or whatnot that comes with a basic server and web UI. All SaaS offerings in this space have completely ridiculous margins and most existing open source solutions are either slow/inefficient or don't support full text search (though there is [loghouse](https://github.com/flant/loghouse)).

**Comment by virattara** [comment]
Apologies for the embarrassing delay.

Personally for me it's sad seeing `LocustDB` go on the back burner. Every time I open its code, I'm awestruck by the efforts that might have gone into developing it. I absolutely love it! I hope the project sees the light of the day, beyond experimentations. Two years ago I pitched it to my employer as a replacement of some of our analytics on BigQuery. But analytics of our product was one of the things that had reached maturity in terms of development. Any change would have meant putting an enormous amount of work load on a small team. I hope `LocustDB` find its niche in this ever-growing db market.

**Comment by cswinter** [comment]
Wow, thanks for the high praise! I don't think you have anything to apologize for. I appreciate all the contributions you've made already, time is a precious resource and I'm honored you chose to spend some of yours on LocustDB ❤️

Even without seeing direct use, LocustDB has already had a significant impact. Given how many people read my blogs its lessons are bound to make their way into future projects and I know of several teams working on proprietary analytics systems that took a keen interest. It's unlikely LocustDB will ever replace the core use cases of something like BigQuery, which has received orders-of-magnitude more investment and solved many very hard problems (joins, durability, integrations, extensive query functionality, documentation, ...). I do think LocustDB's speed and flexible/automatic schema make it suitable for an important and currently poorly served niche for real-time metrics/logs/ad-hoc debugging in distributed systems. Just spin up a LocustDB server, point your logging client at it, and immediately have a nice web UI where you can analyze all of your logs/metrics in real-time. LocustDB already has all the core functionality to do this, it's just missing the surrounding pieces (logging clients, documentation, server and website, easy-to-deploy docker image, ...). Still a lot of work, but I think at least creating an MVP is quite doable. I'm planning to give this a shot after my current project which I hope to wrap up within the next few months.
