### ISSUE TITLE
Unable to build `LocustDB` on Mac OS X

### ISSUE THREAD

**Issue by zhzy0077** [cswinter/LocustDB#114]
After the recently update on `rust-toolchain` at https://github.com/cswinter/LocustDB/commit/28c5cc9f797e00357ce9e04f0e55c1d3236ae764.
Mac OS X will trigger a link error on building even after installed jemalloc `brew install jemalloc`.

The detail log is attached.
```
Undefined symbols for architecture x86_64:
            "_je_malloc_usable_size", referenced from:
                heapsize::heap_size_of_impl::h06f9a1e9b25e97c0 in libheapsize-aba9b641adeff33b.rlib(heapsize-aba9b641adeff33b.heapsize.6qnojmfe-cgu.4.rcgu.o)
          ld: symbol(s) not found for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I have done some investigations:
1. After Nov. 2018, rust nightly removed built-in jemalloc allocator https://internals.rust-lang.org/t/jemalloc-was-just-removed-from-the-standard-library/8759
2. The `heapsize` crate heavily relies on `jemalloc`. And it will fail to link w/o jemalloc. https://github.com/servo/heapsize/issues/80 . This issue has been marked as wontfix.
3. There is a similar issue on `parity-ethereum`, https://github.com/paritytech/parity-ethereum/issues/9167 which is still open.

I still have no idea about how to fix this stuff.

**Comment by cswinter** [comment]
We could try switching the allocator back to jemalloc as per: https://doc.rust-lang.org/1.9.0/book/custom-allocators.html

**Comment by cswinter** [comment]
I had a go at it and it doesn't seem to be super easy to make this work, might be better to just remove the Heapsize dependency entirely. The only use of it right now is to get (approximate) size of data stored in memory, which is dominated by the `DataSection` structs in `Column`. Just estimating their memory usage with `Vec::capacity() * std::mem::size_of` should work well enough. It wouldn't account for allocator overhead, but it was never quite clear to me what exactly the heapsize crate did in that regard anyway.

**Comment by zhzy0077** [comment]
Yep, I have tried many days but eventually failed. `heapsize` has hard-coded link name on Mac OS X(https://github.com/servo/heapsize/blob/master/src/lib.rs#L44). After the removal of jemalloc, It's difficult to make this function available for rust to be linked. 
In the future, if we want to have fine-grained control of memory, we can benefit from https://github.com/servo/servo/tree/master/components/malloc_size_of which is currently used by `Servo`.

**Comment by zhzy0077** [comment]
I have create a pr for this. Please have a look. https://github.com/cswinter/LocustDB/pull/115
