### ISSUE TITLE
Logo?

### ISSUE THREAD

**Issue by apavlo** [cswinter/LocustDB#121]
I have added LocustDB to my encyclopedia of databases:

https://dbdb.io/db/locustdb

Do you have a logo that I can include? Thanks!

-- Andy

**Comment by cswinter** [comment]
Neat! Please have this adorable little grasshopper that I just found :D
![locust](https://img.icons8.com/ultraviolet/50/000000/grasshopper.png)

**Comment by apavlo** [comment]
Do you have a larger version or a vector image?

**Comment by cswinter** [comment]
No vector image unfortunately, but here's some larger versions:
![locust](https://img.icons8.com/ultraviolet/100/000000/grasshopper.png)
![locust](https://img.icons8.com/ultraviolet/200/000000/grasshopper.png)
![locust](https://img.icons8.com/ultraviolet/400/000000/grasshopper.png)
