### ISSUE TITLE
No such subcommand: `+nightly`

### ISSUE THREAD

**Issue by marklit** [cswinter/LocustDB#14]
I'm seeing the following error when following your README install notes.

```bash
$ RUSTFLAGS="-Ccodegen-units=1" CARGO_INCREMENTAL=0 cargo +nightly run --release --bin repl -- test_data/nyc-taxi.csv.gz
```

```
error: no such subcommand: `+nightly`
```

I'm on Ubuntu 16 with the following packages installed:

```
$ sudo apt install curl git cargo make
$ curl https://sh.rustup.rs -sSf | sh
```

**Comment by cswinter** [comment]
Hmm, maybe installing `cargo` via apt resulted in an old version? What does `cargo -V` and `rustc -V` output? (should be at least 1.26.0)

A few potential fixes/workarounds:
- `rustup update`
- substitute`cargo +nightly` with  `rustup run nightly cargo`
- run `rustup toolchain install nightly` and `rustup default nightly` to use nightly toolchain by default, at which point you can omit `+nightly` from all commands

**Comment by cswinter** [comment]
I tried to reproduce, and indeed apt will install cargo `0.26.0` and cause the rustup script to fail because it finds an existing rust installation. This command seems to allow the old installation to be replaced:
```
curl https://sh.rustup.rs -sSf | RUSTUP_INIT_SKIP_PATH_CHECK=yes sh
```

**Comment by marklit** [comment]
That's sorted the issue, thank you.
