### ISSUE TITLE
Panics! Panics everywhere!

### ISSUE THREAD

**Issue by cswinter** [cswinter/LocustDB#2]
```
$ find . -name '*.rs' | xargs grep panic | wc -l
62
```
Make this number go down by replacing `panic`s with `Result`s and bubbling them up to the toplevel.
The biggest offenders are the `cast_*` methods on `AnyVec` and the factory methods on `impl VecOperator`.
There's plenty of `unwrap`s also.

**Comment by narendravardi** [comment]
@cswinter can i pick this task?

**Comment by cswinter** [comment]
You certainly can, much appreciated!
